### PR TITLE
Migrated to .NET Standard

### PR DESCRIPTION
**Pull request by mglace**
I migrated the webhooks library to .NET Standard and the test project to .NET Core (that was the only way I could get the tests to run).  I referenced the newly migrated webhooks library from my .NET Core website and everything ran beautifully.  Bumped the version number to 2.0.0.  Let me know if you need anything else.

### CODE REVIEW

**Comment by Neonkiller** [comment]
Any updates on this? Anybody plan to finish this?

**Comment by m0sa** [comment]
bump

**Comment by mglace** [comment]
I couldn't get the build server to build the project after the port to .NET Standard.  If anyone would like to help, please let me know.

**Comment by m0sa** [comment]
@mglace I got it working in #34

**Comment by mirajavora** [comment]
Merged in #34

**Pull request closed without merging**
