### PR TITLE
netstandard support

### PR DESCRIPTION
**Pull request by m0sa**
netstandard support

### CODE REVIEW

**Comment by m0sa** [comment]
https://github.com/dotnet/sdk/issues/335

**Comment by m0sa** [comment]
@mirajavora finaly got travis to build, test and package it for net40 and netstandard1.0 (which is >=net45)... Theoretically it could be version 1.2.3, since there are no breaking changes.

Any chance this can get merged in and published to nuget?

**Comment by kinetiq** [comment]
@m0sa Do you know what's going on with Standard support? I am concerned this repo might be abandoned.

**Comment by m0sa** [comment]
@mirajavora awesome, thanks! Any chance you can deploy the nuget package to [nuget.org](https://www.nuget.org/packages/Sendgrid.Webhooks/)?

**Pull request merged**
